reorganize runconf and cmake_init, add section for summitdev

diff --git a/cmake_init b/cmake_init
--- a/cmake_init
+++ b/cmake_init
@@ -6,118 +6,8 @@
 
 SRCDIR=`dirname ${BASH_SOURCE[0]}`
 
-if [ `hostname | cut -c 1-4` == "sith" ]; then
 
-    ########
-    # Sith #
-    ########
-    source /etc/profile.d/modules.sh
-    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
-
-    if [ -z "$TARGET" ]; then
-        echo "Cannot determine Programming environment. Exit"
-        exit 1
-    fi
-    echo "Configure on SITH for $TARGET env."
-    source /etc/profile.d/modules.sh
-    module unload hdf5
-    module unload netcdf
-    module unload PE-gnu
-    module unload PE-pgi
-    module unload PE-intel
-    module unload PE-pathscale
-    module unload pgi gcc intel pathscale
-    module unload python
-    module load PE-$TARGET
-    module load python
-    module load szip
-    module load bzip2
-    export LUSTRE_DIR="/usr/lib64"
-#    export FGR_DIR="/ccs/proj/e2e/qliu/tap"
-    export GLIB_DIR="/ccs/proj/e2e/qliu/glib"
-    export BUILD_WRITE=ON
-    export BUILD_FORTRAN=ON
-    export adios_timers=ON
-    export research_transports=ON
-    export CC=mpicc
-    export CXX=mpiCC
-    export FC=mpif90
-    export INSTALL_PREFIX="/ccs/home/jya/ADIOS/sith.$TARGET"
-    export APLOD_DIR="/ccs/proj/e2e/ncsu/sith.gnu"
-    export ISOBAR_DIR="/ccs/proj/e2e/ncsu/sith.gnu"
-    export ALACRITY_DIR="/ccs/proj/e2e/pnorbert/ALACRITY-ADIOS/synced/build.sith/build.gnu" 
-    export NCSU_TIMER_DIR
-    if [ "$TARGET" == "pgi" ]; then
-        module load hdf5/1.8.10
-        export SEQ_HDF5_DIR=$HDF5_DIR
-        export SEQ_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_pgi12.8/lib -L/sw/sith/szip/2.1/rhel6_pgi12.8/lib -lhdf5_hl -lhdf5 -lsz -lz -lm"
-        module unload hdf5/1.8.10
-        module load hdf5/1.8.10_par
-        export PAR_HDF5_DIR=$HDF5_DIR
-        export PAR_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_pgi13.4_ompi1.6.3/lib -L/sw/sith/szip/2.1/rhel6_pgi13.4/lib -lhdf5_hl -lhdf5 -lsz -lz -lm"
-        module unload hdf5/1.8.10_par
-        module load netcdf/4.1.3
-        export SEQ_NC_DIR=$NETCDF_DIR
-        export SEQ_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_pgi12.8/lib -L/sw/sith/hdf5/1.8.10/rhel6_pgi12.8/lib -L/sw/sith/szip/2.1/rhel6_pgi12.8/lib -lnetcdf -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
-        module unload netcdf/4.1.3
-        module load netcdf/4.1.3_par
-        export PAR_NC_DIR=$NETCDF_DIR
-        export PAR_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_pgi13.4_ompi1.6.3/lib -L/sw/sith/hdf5/1.8.10/rhel6_pgi13.4_ompi1.6.3/lib -L/sw/sith/szip/2.1/rhel6_pgi13.4/lib -lnetcdf -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
-        module unload netcdf/4.1.3_par
-
-        export DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith/$TARGET"
-        export FLEXPATH_DIR="/ccs/proj/e2e/chaos/sith/$TARGET"
-        export FASTBIT_DIR="/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
-    elif [ "$TARGET" == "gnu" ]; then
-        module load hdf5/1.8.10
-        export SEQ_HDF5_DIR=$HDF5_DIR
-        export SEQ_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_gnu4.7.1/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_gnu4.7.1/lib -lsz -lz -lm"
-        module unload hdf5/1.8.10
-        module load hdf5/1.8.10_par
-        export PAR_HDF5_DIR=$HDF5_DIR
-        export PAR_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_gnu4.7.1_ompi1.6.3/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_gnu4.7.1/lib -lsz -lz -lm"
-        module unload hdf5/1.8.10_par
-        module load netcdf/4.1.3
-        export SEQ_NC_DIR=$NETCDF_DIR
-        export SEQ_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_gnu4.7.1/lib -L/sw/sith/hdf5/1.8.10/rhel6_gnu4.7.1/lib -L/sw/sith/szip/2.1/rhel6_gnu4.7.1/lib -lnetcdf -lm -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
-        module unload netcdf/4.1.3
-#        module load netcdf/4.1.3_par
-#        export PAR_NC_DIR=$NETCDF_DIR
-#        export PAR_NC_LIBS=""
-#        module unload netcdf/4.1.3_par
-#        export DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith/$TARGET"
-        export FLEXPATH_DIR="/ccs/proj/e2e/chaos/sith/$TARGET"
-        export FASTBIT_DIR="/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
-    elif [ "$TARGET" == "intel" ]; then
-        module load hdf5/1.8.10
-        export SEQ_HDF5_DIR=$HDF5_DIR
-        export SEQ_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_intel11.1/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_intel11.1.072/lib -lsz -lz -lm"
-        module unload hdf5/1.8.10
-        module load hdf5/1.8.10_par
-        export PAR_HDF5_DIR=$HDF5_DIR
-        export PAR_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_intel11.1_ompi1.6.3/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_intel11.1.072/lib -lsz -lz -lm"
-        module unload hdf5/1.8.10_par
-        module load netcdf/4.1.3
-        export SEQ_NC_DIR=$NETCDF_DIR
-        export SEQ_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_intel11.1/lib -L/sw/sith/hdf5/1.8.10/rhel6_intel11.1/lib -L/sw/sith/szip/2.1/rhel6_intel11.1.072/lib -lnetcdf -lm -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
-        module unload netcdf/4.1.3
-#        module load netcdf/4.1.3_par
-#        export PAR_NC_DIR=$NETCDF_DIR
-#        export PAR_NC_LIBS=""
-#        module unload netcdf/4.1.3_par
-#        export DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith/$TARGET"
-        export FLEXPATH_DIR=
-    else
-        echo "TARGET must be pgi or gnu or intel"
-        exit 1
-    fi
-        
-    export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK" 
-    export CFLAGS="-g -fPIC" 
-    cmake $SRCDIR
-
-
-elif [ `hostname | cut -c 1-4` == "rhea" ]; then
+if [ `hostname | cut -c 1-4` == "rhea" ]; then
     source /etc/profile.d/modules.sh
     source /etc/profile.d/modules.sh
     TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
@@ -389,7 +279,148 @@ elif [ `hostname | cut -c 1-7` == "chester" ]; then
       fi
       export CFLAGS="-g -fPIC" 
       cmake $SRCDIR
-            
+
+elif [ `hostname -f | cut -c 1-9` == "summitdev" ]; then
+    #####################
+    #  SUMMITDEV IBM    #
+    #####################
+    MLIST=`module list 2>&1 ` #| grep "PrgEnv"- | sed "s/^.*PrgEnv-\([a-z]*\).*/\1/"`
+    TARGET=`echo $MLIST | grep " xl\/" | sed "s/^.* xl\/.*/xl/"`
+    if [ -z $TARGET ]; then
+        TARGET=`echo $MLIST | grep " pgi\/" | sed "s/^.* pgi\/.*/pgi/"`
+        if [ -z $TARGET ]; then
+            TARGET=`echo $MLIST | grep " gcc\/" | sed "s/^.* gcc\/.*/gcc/"`
+        fi
+    fi
+    echo "Configure on Summitdev for $TARGET env."
+
+    export MPICC=mpicc
+    export MPCXX=mpic++
+    export MPIFC=mpif90
+    export CFLAGS="-g -O0"
+
+    if [ "$TARGET" == "xl" ]; then
+        #export LIBS="-lrdmacm -libverbs"
+        export DATASPACES_DIR=/ccs/proj/e2e/dataspaces/summitdev/1.6.1/xl
+    elif [ "$TARGET" == "pgi" ]; then
+        export DATASPACES_DIR=/ccs/proj/e2e/dataspaces/summitdev/1.6.1/pgi
+    elif [ "$TARGET" == "gcc" ]; then
+        export DATASPACES_DIR=/ccs/proj/e2e/dataspaces/summitdev/1.6.1/gcc
+    fi
+
+    export INSTALL_PREFIX=/ccs/proj/e2e/pnorbert/ADIOS/summitdev.$TARGET  
+    cmake $SRCDIR
+
+elif [ `hostname | cut -c 1-4` == "sith" ]; then
+
+    ########
+    # Sith #
+    ########
+    source /etc/profile.d/modules.sh
+    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
+
+    if [ -z "$TARGET" ]; then
+        echo "Cannot determine Programming environment. Exit"
+        exit 1
+    fi
+    echo "Configure on SITH for $TARGET env."
+    source /etc/profile.d/modules.sh
+    module unload hdf5
+    module unload netcdf
+    module unload PE-gnu
+    module unload PE-pgi
+    module unload PE-intel
+    module unload PE-pathscale
+    module unload pgi gcc intel pathscale
+    module unload python
+    module load PE-$TARGET
+    module load python
+    module load szip
+    module load bzip2
+    export LUSTRE_DIR="/usr/lib64"
+#    export FGR_DIR="/ccs/proj/e2e/qliu/tap"
+    export GLIB_DIR="/ccs/proj/e2e/qliu/glib"
+    export BUILD_WRITE=ON
+    export BUILD_FORTRAN=ON
+    export adios_timers=ON
+    export research_transports=ON
+    export CC=mpicc
+    export CXX=mpiCC
+    export FC=mpif90
+    export INSTALL_PREFIX="/ccs/home/jya/ADIOS/sith.$TARGET"
+    export APLOD_DIR="/ccs/proj/e2e/ncsu/sith.gnu"
+    export ISOBAR_DIR="/ccs/proj/e2e/ncsu/sith.gnu"
+    export ALACRITY_DIR="/ccs/proj/e2e/pnorbert/ALACRITY-ADIOS/synced/build.sith/build.gnu" 
+    export NCSU_TIMER_DIR
+    if [ "$TARGET" == "pgi" ]; then
+        module load hdf5/1.8.10
+        export SEQ_HDF5_DIR=$HDF5_DIR
+        export SEQ_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_pgi12.8/lib -L/sw/sith/szip/2.1/rhel6_pgi12.8/lib -lhdf5_hl -lhdf5 -lsz -lz -lm"
+        module unload hdf5/1.8.10
+        module load hdf5/1.8.10_par
+        export PAR_HDF5_DIR=$HDF5_DIR
+        export PAR_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_pgi13.4_ompi1.6.3/lib -L/sw/sith/szip/2.1/rhel6_pgi13.4/lib -lhdf5_hl -lhdf5 -lsz -lz -lm"
+        module unload hdf5/1.8.10_par
+        module load netcdf/4.1.3
+        export SEQ_NC_DIR=$NETCDF_DIR
+        export SEQ_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_pgi12.8/lib -L/sw/sith/hdf5/1.8.10/rhel6_pgi12.8/lib -L/sw/sith/szip/2.1/rhel6_pgi12.8/lib -lnetcdf -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
+        module unload netcdf/4.1.3
+        module load netcdf/4.1.3_par
+        export PAR_NC_DIR=$NETCDF_DIR
+        export PAR_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_pgi13.4_ompi1.6.3/lib -L/sw/sith/hdf5/1.8.10/rhel6_pgi13.4_ompi1.6.3/lib -L/sw/sith/szip/2.1/rhel6_pgi13.4/lib -lnetcdf -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
+        module unload netcdf/4.1.3_par
+
+        export DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith/$TARGET"
+        export FLEXPATH_DIR="/ccs/proj/e2e/chaos/sith/$TARGET"
+        export FASTBIT_DIR="/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
+    elif [ "$TARGET" == "gnu" ]; then
+        module load hdf5/1.8.10
+        export SEQ_HDF5_DIR=$HDF5_DIR
+        export SEQ_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_gnu4.7.1/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_gnu4.7.1/lib -lsz -lz -lm"
+        module unload hdf5/1.8.10
+        module load hdf5/1.8.10_par
+        export PAR_HDF5_DIR=$HDF5_DIR
+        export PAR_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_gnu4.7.1_ompi1.6.3/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_gnu4.7.1/lib -lsz -lz -lm"
+        module unload hdf5/1.8.10_par
+        module load netcdf/4.1.3
+        export SEQ_NC_DIR=$NETCDF_DIR
+        export SEQ_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_gnu4.7.1/lib -L/sw/sith/hdf5/1.8.10/rhel6_gnu4.7.1/lib -L/sw/sith/szip/2.1/rhel6_gnu4.7.1/lib -lnetcdf -lm -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
+        module unload netcdf/4.1.3
+#        module load netcdf/4.1.3_par
+#        export PAR_NC_DIR=$NETCDF_DIR
+#        export PAR_NC_LIBS=""
+#        module unload netcdf/4.1.3_par
+#        export DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith/$TARGET"
+        export FLEXPATH_DIR="/ccs/proj/e2e/chaos/sith/$TARGET"
+        export FASTBIT_DIR="/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
+    elif [ "$TARGET" == "intel" ]; then
+        module load hdf5/1.8.10
+        export SEQ_HDF5_DIR=$HDF5_DIR
+        export SEQ_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_intel11.1/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_intel11.1.072/lib -lsz -lz -lm"
+        module unload hdf5/1.8.10
+        module load hdf5/1.8.10_par
+        export PAR_HDF5_DIR=$HDF5_DIR
+        export PAR_HDF5_LIBS="-L/sw/sith/hdf5/1.8.10/rhel6_intel11.1_ompi1.6.3/lib -lhdf5_hl -lhdf5 -L/sw/sith/szip/2.1/rhel6_intel11.1.072/lib -lsz -lz -lm"
+        module unload hdf5/1.8.10_par
+        module load netcdf/4.1.3
+        export SEQ_NC_DIR=$NETCDF_DIR
+        export SEQ_NC_LIBS="-L/sw/sith/netcdf/4.1.3/rhel6_intel11.1/lib -L/sw/sith/hdf5/1.8.10/rhel6_intel11.1/lib -L/sw/sith/szip/2.1/rhel6_intel11.1.072/lib -lnetcdf -lm -lcurl -lhdf5_hl -lhdf5 -lsz -lz -lm"
+        module unload netcdf/4.1.3
+#        module load netcdf/4.1.3_par
+#        export PAR_NC_DIR=$NETCDF_DIR
+#        export PAR_NC_LIBS=""
+#        module unload netcdf/4.1.3_par
+#        export DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith/$TARGET"
+        export FLEXPATH_DIR=
+    else
+        echo "TARGET must be pgi or gnu or intel"
+        exit 1
+    fi
+        
+    export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK" 
+    export CFLAGS="-g -fPIC" 
+    cmake $SRCDIR
+
 
 elif [ "x"`hostname -f | cut -c 8-15` == "xintrepid" ]; then
     #####################
diff --git a/runconf b/runconf
--- a/runconf
+++ b/runconf
@@ -6,131 +6,7 @@
 
 SRCDIR=`dirname ${BASH_SOURCE[0]}`
 
-if [ `hostname | cut -c 1-4` == "sith" ]; then
-
-    ########
-    # Sith #
-    ########
-    source /etc/profile.d/modules.sh
-    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
-
-    if [ -z "$TARGET" ]; then
-        echo "Cannot determine Programming environment. Exit"
-        exit 1
-    fi
-    echo "Configure on SITH for $TARGET env. for user ${USER}"
-    module unload hdf5
-    module unload netcdf
-    module unload python
-    #module unload PE-gnu
-    #module unload PE-pgi
-    #module unload PE-intel
-    #module unload PE-pathscale
-    #module unload pgi gcc intel pathscale
-    #module load PE-$TARGET
-    module load python
-    # Use both seq hdf5 (for utils) and 
-    #   parallel hdf5 (for PHDF5 method)
-    module load hdf5/1.8.10
-    SEQ_HDF5_DIR=$HDF5_DIR
-    SEQ_HDF5_CLIB=$HDF5_CLIB
-    module unload hdf5
-    module load hdf5/1.8.10_par
-    PAR_HDF5_DIR=$HDF5_DIR
-    PAR_HDF5_CLIB=$HDF5_CLIB
-    module unload hdf5
-    # Seq. and Parallel NetCDF 4 
-    module load netcdf/4.1.3
-    SEQ_NC_DIR=$NETCDF_DIR
-    SEQ_NC_CLIB=$NETCDF_CLIB
-    module unload netcdf
-    module load netcdf/4.1.3_par
-    PAR_NC_DIR=$NETCDF_DIR
-    PAR_NC_CLIB=$NETCDF_CLIB
-    module unload netcdf
-    #module load szip
-    module load bzip2
-    module unload dataspaces
-    unset DATASPACES_DIR
-    module load dataspaces/1.6.0
-    export MPICC=mpicc
-    export MPICXX=mpiCC
-    export MPIFC=mpif90
-    export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK" 
-    export CFLAGS="-g -O0 -fPIC" 
-    export CXXFLAGS="-g -O0 -fPIC" 
-    export FCFLAGS="-g -O0 -fPIC" 
-    WITHFLEX=""
-    WITHFGR=""
-    WITHFASTBIT=""
-    WITHALACRITY=""
-    if [ "$TARGET" == "pgi" ]; then
-        export CC=pgcc
-        export CXX=pgCC
-        export FC=pgf90
-        WITHFLEX="--with-flexpath=/ccs/proj/e2e/chaos/sith/$TARGET"
-        WITHFGR="--with-fgr=/ccs/proj/e2e/qliu/tap" 
-        WITHALACRITY="--with-alacrity=/ccs/proj/e2e/ncsu/alacrity/sith/pgi"
-        WITHFASTBIT="--with-fastbit=/sw/redhat6/fastbit/svn/rhel6_gnu4.4.7"
-        #DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith-tcp/1.6.pgi"
-        #DATASPACES_DIR="/ccs/home/hbui/usr/software/dataspaces-dev"
-    elif [ "$TARGET" == "gnu" ]; then
-        export CC=gcc
-        export CXX=g++
-        export FC=gfortran
-        #export CFLAGS="$CFLAGS -gdwarf-3" 
-        #export FCFLAGS="$FCFLAGS -gdwarf-3" 
-        WITHFLEX="--with-flexpath=/ccs/proj/e2e/chaos/sith/$TARGET"
-        WITHALACRITY="--with-alacrity=/ccs/proj/e2e/ncsu/alacrity/sith/gnu"
-        WITHFASTBIT="--with-fastbit=/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
-        #DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith-tcp/1.6.gnu"
-    elif [ "$TARGET" == "intel" ]; then
-        export CC=icc
-        export CXX=icpc
-        export FC=ifort
-        WITHALACRITY="--with-alacrity=/ccs/proj/e2e/ncsu/alacrity/sith/intel"
-        WITHFASTBIT="--with-fastbit=/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
-    else
-        echo "TARGET must be pgi or gnu or intel"
-        exit 1
-    fi
-        
-    $SRCDIR/configure --prefix=/ccs/proj/e2e/${USER}/ADIOS/sith.$TARGET \
-        --config-cache \
-        --disable-maintainer-mode \
-        --enable-dependency-tracking \
-        --enable-research-transports \
-        --with-lustre \
-        --with-hdf5=${SEQ_HDF5_DIR} \
-        --with-hdf5-libs="${SEQ_HDF5_CLIB}" \
-        --with-zlib \
-        --with-bzip2=$BZIP2_DIR \
-        --with-dataspaces=$DATASPACES_DIR \
-        $WITHFLEX \
-        $WITHFASTBIT \
-        $WITHALACRITY \
-        --with-aplod=/ccs/proj/e2e/ncsu/sith.gnu \
-        --with-isobar=/ccs/proj/e2e/ncsu/sith.gnu \
-        #$WITHFASTBIT \
-        #--with-netcdf=${SEQ_NC_DIR} \
-        #--with-netcdf-libs="${SEQ_NC_CLIB}" \
-        #--with-dimes=$DATASPACES_DIR \
-        #--with-glib=/ccs/proj/e2e/qliu/glib
-        #$WITHFGR \
-        #--with-szip=$SZIP_DIR \
-        #--with-phdf5=${PAR_HDF5_DIR} \
-        #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
-        #--with-nc4par=${PAR_NC_DIR} \
-        #--with-nc4par-libs="${PAR_NC_CLIB}" \
-        #--with-dmalloc=/ccs/proj/e2e/qliu/dmalloc.sith.$TARGET 
-        #--with-dmalloc=/ccs/proj/e2e/pnorbert/dmalloc.$TARGET 
-        #--enable-shared --disable-static
-        #--without-datatap #--without-infiniband
-        #--with-dmalloc=/ccs/proj/e2e/pnorbert/dmalloc.$TARGET 
-        #--with-datatap=/ccs/home/habbasi/work/ewok/
-        #--enable-datatap=ib
-
-elif [ `hostname | cut -c 1-4` == "rhea" ]; then
+if [ `hostname | cut -c 1-4` == "rhea" ]; then
 
     ########
     # Rhea #
@@ -214,8 +90,8 @@ elif [ `hostname | cut -c 1-4` == "rhea" ]; then
         --with-zlib \
         --with-bzip2 \
         --with-fastbit=$FASTBIT_DIR \
-        #--with-hdf5=${SEQ_HDF5_DIR} \
-        #--with-hdf5-libs="${SEQ_HDF5_CLIB}" \
+        --with-hdf5=${SEQ_HDF5_DIR} \
+        --with-hdf5-libs="${SEQ_HDF5_CLIB}" \
         #--with-phdf5=${PAR_HDF5_DIR} \
         #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
         #--with-netcdf=${SEQ_NC_DIR} \
@@ -227,91 +103,6 @@ elif [ `hostname | cut -c 1-4` == "rhea" ]; then
         #--with-fgr=/ccs/proj/e2e/qliu/tap \
         #--with-glib=/ccs/proj/e2e/qliu/glib
         #--with-szip=$SZIP_DIR \
-
-elif [ `hostname | cut -c 1-4` == "yona" ]; then
-
-    ########
-    # Yona #
-    ########
-    source /etc/profile.d/modules.sh
-    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
-    echo "Configure on Yona for $TARGET env."
-    module unload hdf5
-    module unload netcdf
-    module unload PE-gnu
-    module unload PE-pgi
-    module unload PE-intel
-    module unload PE-pathscale
-    module unload pgi gcc intel pathscale
-    #module unload python
-    module load PE-$TARGET
-    #module load python
-    # Use both seq hdf5 (for utils) and 
-    #   parallel hdf5 (for PHDF5 method)
-    module load hdf5/1.8.5
-    SEQ_HDF5_DIR=$HDF5_DIR
-    SEQ_HDF5_CLIB=$HDF5_CLIB
-    module unload hdf5
-    #module load hdf5/1.8.5_par
-    #PAR_HDF5_DIR=$HDF5_DIR
-    #PAR_HDF5_CLIB=$HDF5_CLIB
-    #module unload hdf5
-    # Seq. and Parallel NetCDF 4 
-    module load netcdf/3.6.2
-    SEQ_NC_DIR=$NETCDF_DIR
-    SEQ_NC_CLIB=$NETCDF_CLIB
-    module unload netcdf
-    #module load netcdf/4.1.1_par
-    #PAR_NC_DIR=$NETCDF_DIR
-    #PAR_NC_CLIB=$NETCDF_CLIB
-    #module unload netcdf
-    export MPICC=mpicc
-    export MPICXX=mpiCC
-    export MPIFC=mpif90
-    if [ "$TARGET" == "pgi" ]; then
-        export CC=pgcc
-        export CXX=pgCC
-        export FC=pgf90
-    elif [ "$TARGET" == "gnu" ]; then
-        export CC=gcc
-        export CXX=g++
-        export FC=gfortran
-    elif [ "$TARGET" == "intel" ]; then
-        export CC=pgcc
-        export CXX=pgCC
-        export FC=pgf90
-    elif [ "$TARGET" == "gnu" ]; then
-        export CC=gcc
-        export CXX=g++
-        export FC=gfortran
-    elif [ "$TARGET" == "intel" ]; then
-        export CC=icc
-        export CXX=icpc
-        export FC=ifort
-    else
-        echo "TARGET must be pgi or gnu or intel"
-        exit 1
-    fi
-        
-    export CFLAGS="-g -fPIC" 
-    ${SRCDIR}/configure --prefix=/ccs/proj/e2e/pnorbert/ADIOS/yona.$TARGET \
-        --config-cache \
-        --disable-maintainer-mode \
-        --enable-dependency-tracking \
-        --enable-research-transports  \
-        --with-hdf5=${SEQ_HDF5_DIR} \
-        --with-hdf5-libs="${SEQ_HDF5_CLIB}" \
-        --with-netcdf=${SEQ_NC_DIR} \
-        --with-netcdf-libs="${SEQ_NC_CLIB}" \
-        --with-lustre=/usr \
-        --without-datatap --without-infiniband
-        #--with-phdf5=${PAR_HDF5_DIR} \
-        #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
-        #--with-nc4par=${PAR_NC_DIR} \
-        #--with-nc4par-libs="${PAR_NC_CLIB}" \
-        #--with-dmalloc=/ccs/proj/e2e/pnorbert/dmalloc.$TARGET 
-        #--with-datatap=/ccs/home/habbasi/work/ewok/
-        #--enable-datatap=ib
 
 
 elif [ `hostname | cut -c 1-5` == "titan" ]; then
@@ -351,7 +142,7 @@ elif [ `hostname | cut -c 1-5` == "titan" ]; then
         export EXTRA_CFLAGS="-fast"
         #DATASPACES_DIR="/ccs/proj/e2e/dataspaces/titan/$target-cpu"
         module load flexpath/stable
-        WITHFLEX="--with-flexpath=$FLEXPATH_DIR"
+        #WITHFLEX="--with-flexpath=$FLEXPATH_DIR"
     elif [ "$TARGET" == "gnu" ]; then
         #export CC=gcc
         #export FC=gfortran
@@ -537,6 +328,270 @@ elif [ `hostname | cut -c 1-7` == "chester" ]; then
 #            --with-hdf5=/sw/xt5/hdf5/1.8.2/cnl2.1_gnu4.2.0 \
 #          --with-cray-ugni-incdir=/opt/cray/gni-headers/2.1-1.0400.4351.3.1.gem/include \
             
+
+elif [ `hostname -f | cut -c 1-9` == "summitdev" ]; then
+    #####################
+    #  SUMMITDEV IBM    #
+    #####################
+    MLIST=`module list 2>&1 ` #| grep "PrgEnv"- | sed "s/^.*PrgEnv-\([a-z]*\).*/\1/"`
+    TARGET=`echo $MLIST | grep " xl\/" | sed "s/^.* xl\/.*/xl/"`
+    if [ -z $TARGET ]; then
+        TARGET=`echo $MLIST | grep " pgi\/" | sed "s/^.* pgi\/.*/pgi/"`
+        if [ -z $TARGET ]; then
+            TARGET=`echo $MLIST | grep " gcc\/" | sed "s/^.* gcc\/.*/gcc/"`
+        fi
+    fi
+    echo "Configure on Summitdev for $TARGET env."
+    
+    unset WITH_DATASPACES
+    if [ "$TARGET" == "xl" ]; then
+        export MPICC=mpicc
+        export MPCXX=mpic++
+        export MPIFC=mpif90
+        export CFLAGS="-g -O0"
+        export FC=xlf90
+        export CC=xlc
+        export CXX=xlC
+        #export LIBS="-lrdmacm -libverbs"
+        DATASPACES_DIR=/ccs/proj/e2e/dataspaces/summitdev/1.6.1/xl
+        #WITH_DATASPACES="--with-dataspaces=$DATASPACES_DIR --with-dimes=$DATASPACES_DIR"
+    elif [ "$TARGET" == "pgi" ]; then
+        export CC=pgcc
+        export FC=pgf90
+        export CXX=pgc++
+        export MPICC=mpicc
+        export MPCXX=mpic++
+        export MPIFC=mpif90
+        export CFLAGS="-g -O0"
+        #DATASPACES_DIR=/ccs/proj/e2e/dataspaces/summitdev/1.6.1/pgi
+        #WITH_DATASPACES="--with-dataspaces=$DATASPACES_DIR --with-dimes=$DATASPACES_DIR"
+    elif [ "$TARGET" == "gcc" ]; then
+        export CC=gcc
+        export FC=gfortran
+        export CXX=g++
+        export MPICC=mpicc
+        export MPCXX=mpic++
+        export MPIFC=mpif90
+        export CFLAGS="-g -O0"
+        DATASPACES_DIR=/ccs/proj/e2e/dataspaces/summitdev/1.6.1/gcc
+        #WITH_DATASPACES="--with-dataspaces=$DATASPACES_DIR --with-dimes=$DATASPACES_DIR"
+    fi
+
+    ${SRCDIR}/configure --prefix=/ccs/proj/e2e/pnorbert/ADIOS/summitdev.$TARGET  \
+            --disable-maintainer-mode \
+            --enable-dependency-tracking \
+            --without-datatap  \
+            $WITH_DATASPACES
+
+elif [ `hostname | cut -c 1-4` == "sith" ]; then
+
+    ########
+    # Sith #
+    ########
+    #source /etc/profile.d/modules.sh
+    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
+
+    if [ -z "$TARGET" ]; then
+        echo "Cannot determine Programming environment. Exit"
+        exit 1
+    fi
+    echo "Configure on SITH for $TARGET env. for user ${USER}"
+    module unload hdf5
+    module unload netcdf
+    module unload python
+    #module unload PE-gnu
+    #module unload PE-pgi
+    #module unload PE-intel
+    #module unload PE-pathscale
+    #module unload pgi gcc intel pathscale
+    #module load PE-$TARGET
+    module load python
+    # Use both seq hdf5 (for utils) and 
+    #   parallel hdf5 (for PHDF5 method)
+    module load hdf5/1.8.10
+    SEQ_HDF5_DIR=$HDF5_DIR
+    SEQ_HDF5_CLIB=$HDF5_CLIB
+    module unload hdf5
+    module load hdf5/1.8.10_par
+    PAR_HDF5_DIR=$HDF5_DIR
+    PAR_HDF5_CLIB=$HDF5_CLIB
+    module unload hdf5
+    # Seq. and Parallel NetCDF 4 
+    module load netcdf/4.1.3
+    SEQ_NC_DIR=$NETCDF_DIR
+    SEQ_NC_CLIB=$NETCDF_CLIB
+    module unload netcdf
+    module load netcdf/4.1.3_par
+    PAR_NC_DIR=$NETCDF_DIR
+    PAR_NC_CLIB=$NETCDF_CLIB
+    module unload netcdf
+    #module load szip
+    module load bzip2
+    module unload dataspaces
+    unset DATASPACES_DIR
+    module load dataspaces/1.6.0
+    export MPICC=mpicc
+    export MPICXX=mpiCC
+    export MPIFC=mpif90
+    export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK" 
+    export CFLAGS="-g -O0 -fPIC" 
+    export CXXFLAGS="-g -O0 -fPIC" 
+    export FCFLAGS="-g -O0 -fPIC" 
+    WITHFLEX=""
+    WITHFGR=""
+    WITHFASTBIT=""
+    WITHALACRITY=""
+    if [ "$TARGET" == "pgi" ]; then
+        export CC=pgcc
+        export CXX=pgc++
+        export FC=pgf90
+        WITHFLEX="--with-flexpath=/ccs/proj/e2e/chaos/sith/$TARGET"
+        WITHFGR="--with-fgr=/ccs/proj/e2e/qliu/tap" 
+        WITHALACRITY="--with-alacrity=/ccs/proj/e2e/ncsu/alacrity/sith/pgi"
+        WITHFASTBIT="--with-fastbit=/sw/redhat6/fastbit/svn/rhel6_gnu4.4.7"
+        #DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith-tcp/1.6.pgi"
+        #DATASPACES_DIR="/ccs/home/hbui/usr/software/dataspaces-dev"
+    elif [ "$TARGET" == "gnu" ]; then
+        export CC=gcc
+        export CXX=g++
+        export FC=gfortran
+        #export CFLAGS="$CFLAGS -gdwarf-3" 
+        #export FCFLAGS="$FCFLAGS -gdwarf-3" 
+        WITHFLEX="--with-flexpath=/ccs/proj/e2e/chaos/sith/$TARGET"
+        WITHALACRITY="--with-alacrity=/ccs/proj/e2e/ncsu/alacrity/sith/gnu"
+        WITHFASTBIT="--with-fastbit=/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
+        #DATASPACES_DIR="/ccs/proj/e2e/dataspaces/sith-tcp/1.6.gnu"
+    elif [ "$TARGET" == "intel" ]; then
+        export CC=icc
+        export CXX=icpc
+        export FC=ifort
+        WITHALACRITY="--with-alacrity=/ccs/proj/e2e/ncsu/alacrity/sith/intel"
+        WITHFASTBIT="--with-fastbit=/sw/redhat6/fastbit/svn/rhel6_gnu4.8.2"
+    else
+        echo "TARGET must be pgi or gnu or intel"
+        exit 1
+    fi
+        
+    $SRCDIR/configure --prefix=/ccs/proj/e2e/${USER}/ADIOS/sith.$TARGET \
+        --config-cache \
+        --disable-maintainer-mode \
+        --enable-dependency-tracking \
+        --enable-research-transports \
+        --with-lustre \
+        #--with-zlib \
+        #--with-bzip2=$BZIP2_DIR \
+        #--with-dataspaces=$DATASPACES_DIR \
+        #$WITHFLEX \
+        #$WITHFASTBIT \
+        #$WITHALACRITY \
+        #--with-aplod=/ccs/proj/e2e/ncsu/sith.gnu \
+        #--with-isobar=/ccs/proj/e2e/ncsu/sith.gnu \
+        #--with-hdf5=${SEQ_HDF5_DIR} \
+        #--with-hdf5-libs="${SEQ_HDF5_CLIB}" \
+        #--with-netcdf=${SEQ_NC_DIR} \
+        #--with-netcdf-libs="${SEQ_NC_CLIB}" \
+        #--with-dimes=$DATASPACES_DIR \
+        #--with-glib=/ccs/proj/e2e/qliu/glib
+        #$WITHFGR \
+        #--with-szip=$SZIP_DIR \
+        #--with-phdf5=${PAR_HDF5_DIR} \
+        #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
+        #--with-nc4par=${PAR_NC_DIR} \
+        #--with-nc4par-libs="${PAR_NC_CLIB}" \
+        #--with-dmalloc=/ccs/proj/e2e/qliu/dmalloc.sith.$TARGET 
+        #--with-dmalloc=/ccs/proj/e2e/pnorbert/dmalloc.$TARGET 
+        #--enable-shared --disable-static
+        #--without-datatap #--without-infiniband
+        #--with-dmalloc=/ccs/proj/e2e/pnorbert/dmalloc.$TARGET 
+        #--with-datatap=/ccs/home/habbasi/work/ewok/
+        #--enable-datatap=ib
+
+elif [ `hostname | cut -c 1-4` == "yona" ]; then
+
+    ########
+    # Yona #
+    ########
+    source /etc/profile.d/modules.sh
+    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
+    echo "Configure on Yona for $TARGET env."
+    module unload hdf5
+    module unload netcdf
+    module unload PE-gnu
+    module unload PE-pgi
+    module unload PE-intel
+    module unload PE-pathscale
+    module unload pgi gcc intel pathscale
+    #module unload python
+    module load PE-$TARGET
+    #module load python
+    # Use both seq hdf5 (for utils) and 
+    #   parallel hdf5 (for PHDF5 method)
+    module load hdf5/1.8.5
+    SEQ_HDF5_DIR=$HDF5_DIR
+    SEQ_HDF5_CLIB=$HDF5_CLIB
+    module unload hdf5
+    #module load hdf5/1.8.5_par
+    #PAR_HDF5_DIR=$HDF5_DIR
+    #PAR_HDF5_CLIB=$HDF5_CLIB
+    #module unload hdf5
+    # Seq. and Parallel NetCDF 4 
+    module load netcdf/3.6.2
+    SEQ_NC_DIR=$NETCDF_DIR
+    SEQ_NC_CLIB=$NETCDF_CLIB
+    module unload netcdf
+    #module load netcdf/4.1.1_par
+    #PAR_NC_DIR=$NETCDF_DIR
+    #PAR_NC_CLIB=$NETCDF_CLIB
+    #module unload netcdf
+    export MPICC=mpicc
+    export MPICXX=mpiCC
+    export MPIFC=mpif90
+    if [ "$TARGET" == "pgi" ]; then
+        export CC=pgcc
+        export CXX=pgCC
+        export FC=pgf90
+    elif [ "$TARGET" == "gnu" ]; then
+        export CC=gcc
+        export CXX=g++
+        export FC=gfortran
+    elif [ "$TARGET" == "intel" ]; then
+        export CC=pgcc
+        export CXX=pgCC
+        export FC=pgf90
+    elif [ "$TARGET" == "gnu" ]; then
+        export CC=gcc
+        export CXX=g++
+        export FC=gfortran
+    elif [ "$TARGET" == "intel" ]; then
+        export CC=icc
+        export CXX=icpc
+        export FC=ifort
+    else
+        echo "TARGET must be pgi or gnu or intel"
+        exit 1
+    fi
+        
+    export CFLAGS="-g -fPIC" 
+    ${SRCDIR}/configure --prefix=/ccs/proj/e2e/pnorbert/ADIOS/yona.$TARGET \
+        --config-cache \
+        --disable-maintainer-mode \
+        --enable-dependency-tracking \
+        --enable-research-transports  \
+        --with-hdf5=${SEQ_HDF5_DIR} \
+        --with-hdf5-libs="${SEQ_HDF5_CLIB}" \
+        --with-netcdf=${SEQ_NC_DIR} \
+        --with-netcdf-libs="${SEQ_NC_CLIB}" \
+        --with-lustre=/usr \
+        --without-datatap --without-infiniband
+        #--with-phdf5=${PAR_HDF5_DIR} \
+        #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
+        #--with-nc4par=${PAR_NC_DIR} \
+        #--with-nc4par-libs="${PAR_NC_CLIB}" \
+        #--with-dmalloc=/ccs/proj/e2e/pnorbert/dmalloc.$TARGET 
+        #--with-datatap=/ccs/home/habbasi/work/ewok/
+        #--enable-datatap=ib
+
+
 
 elif [ `hostname -f | cut -c 1-4` == "mira" ]; then
     #####################
