Merged changes from trunk, now incorporating revision 2156. Also, cleaned up transform code a bit more

diff --git a/runconf b/runconf
--- a/runconf
+++ b/runconf
@@ -32,23 +32,23 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
     module load python
     # Use both seq hdf5 (for utils) and 
     #   parallel hdf5 (for PHDF5 method)
-    module load hdf5/1.8.5
+    module load hdf5/1.8.10
     SEQ_HDF5_DIR=$HDF5_DIR
     SEQ_HDF5_CLIB=$HDF5_CLIB
     module unload hdf5
-    module load hdf5/1.8.5_par
+    module load hdf5/1.8.10_par
     PAR_HDF5_DIR=$HDF5_DIR
     PAR_HDF5_CLIB=$HDF5_CLIB
     module unload hdf5
     # Seq. and Parallel NetCDF 4 
-    module load netcdf/4.1.1
-    SEQ_NC_DIR=$NETCDF_DIR
-    SEQ_NC_CLIB=$NETCDF_CLIB
-    module unload netcdf
-    module load netcdf/4.1.1_par
-    PAR_NC_DIR=$NETCDF_DIR
-    PAR_NC_CLIB=$NETCDF_CLIB
-    module unload netcdf
+    #module load netcdf/4.1.1
+    #SEQ_NC_DIR=$NETCDF_DIR
+    #SEQ_NC_CLIB=$NETCDF_CLIB
+    #module unload netcdf
+    #module load netcdf/4.1.1_par
+    #PAR_NC_DIR=$NETCDF_DIR
+    #PAR_NC_CLIB=$NETCDF_CLIB
+    #module unload netcdf
     export MPICC=mpicc
     export MPICXX=mpiCC
     export MPIFC=mpif90
@@ -74,17 +74,17 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
         
     export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK" 
     export CFLAGS="-g -fPIC" 
-    ./configure --prefix=/ccs/proj/e2e/qliu/ADIOS/sith.$TARGET \
+    ./configure --prefix=/ccs/proj/e2e/pnorbert/ADIOS/sith.$TARGET \
         --enable-dependency-tracking \
         --enable-research-transports  \
         --with-lustre=/usr/lib64 \
+        --with-hdf5=${SEQ_HDF5_DIR} \
+        --with-hdf5-libs="${SEQ_HDF5_CLIB}" \
         $WITHDART 
         #--with-dmalloc=/ccs/proj/e2e/qliu/dmalloc.sith.$TARGET 
         #--with-dmalloc=/ccs/proj/e2e/pnorbert/dmalloc.$TARGET 
         #--enable-shared --disable-static
         #--without-datatap #--without-infiniband
-        #--with-hdf5=${SEQ_HDF5_DIR} \
-        #--with-hdf5-libs="${SEQ_HDF5_CLIB}" \
         #--with-phdf5=${PAR_HDF5_DIR} \
         #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
         #--with-netcdf=${SEQ_NC_DIR} \
@@ -110,10 +110,10 @@ elif [ `hostname | cut -c 1-4` == "yona" ]; then
     module unload PE-intel
     module unload PE-pathscale
     module unload pgi gcc intel pathscale
-    module unload python
+    #module unload python
     module load PE-$TARGET
     module load mxml
-    module load python
+    #module load python
     # Use both seq hdf5 (for utils) and 
     #   parallel hdf5 (for PHDF5 method)
     module load hdf5/1.8.5
@@ -181,9 +181,15 @@ elif [ `hostname | cut -c 1-4` == "yona" ]; then
 
 
 elif [ `hostname | cut -c 1-4` == "lens" ]; then
-    TARGET=pgi
-    echo "Configure on LENS for $TARGET env."
     source /etc/profile.d/modules.sh
+    source /etc/profile.d/modules.sh
+    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
+
+    if [ -z "$TARGET" ]; then
+        echo "Cannot determine Programming environment. Exit"
+        exit 1
+    fi
+    echo "Configure on LENS for $TARGET env."
     module unload hdf5
     module unload netcdf
     module unload PE-gnu
@@ -191,15 +197,16 @@ elif [ `hostname | cut -c 1-4` == "lens" ]; then
     module unload PE-pathscale
     module unload pgi
     module load PE-$TARGET
+    module load mxml
     # Use both seq hdf5 (for utils) and 
     #   parallel hdf5 (for PHDF5 method)
-    #module load hdf5/1.8.2
+    module load hdf5/1.8.6
     SEQ_HDF5_DIR=$HDF5_DIR
     SEQ_HDF5_CLIB=$HDF5_CLIB
-    #module unload hdf5
-    #module load hdf5/1.8.2_par
-    PAR_HDF5_DIR=$HDF5_DIR
-    PAR_HDF5_CLIB=$HDF5_CLIB
+    module unload hdf5
+    #module load hdf5/1.8.6_ompi1.4.2
+    #PAR_HDF5_DIR=$HDF5_DIR
+    #PAR_HDF5_CLIB=$HDF5_CLIB
     #module unload hdf5
     # Seq NetCDF 3 for bp2ncd
     #module load netcdf/3.6.2
@@ -221,11 +228,13 @@ elif [ `hostname | cut -c 1-4` == "lens" ]; then
     fi
 
     export CFLAGS="-g -fPIC"
-    ./configure --prefix=/ccs/proj/e2e/qliu/ADIOS/sith.$TARGET \
+    ./configure --prefix=/ccs/proj/e2e/pnorbert/ADIOS/lens.$TARGET \
         --enable-dependency-tracking \
-        --with-mxml=/ccs/proj/e2e/pnorbert/mxml \
         --enable-research-transports  \
+        --with-hdf5=${SEQ_HDF5_DIR} \
+        --with-hdf5-libs="${SEQ_HDF5_CLIB}" \
         --without-datatap
+        #--with-mxml=/ccs/proj/e2e/pnorbert/mxml \
 
 
 elif [ `hostname | cut -c 1-8` == "jaguarpf" ]; then
@@ -681,9 +690,9 @@ elif [ `hostname | cut -c 1-6` == "hopper" ]; then
     ##########
     TARGET=pgi
     echo "Configure on HOPPER for $TARGET env."
-    export CC=cc
-    export CXX=CC
-    export FC=ftn
+    export MPICC=cc
+    export MPICXX=CC
+    export MPIFC=ftn
     module unload hdf5
     module unload netcdf
     module unload hdf5-parallel
@@ -694,18 +703,36 @@ elif [ `hostname | cut -c 1-6` == "hopper" ]; then
     module unload PrgEnv-cray
     TARGET=pgi
     module load PrgEnv-$TARGET
-    #if [ "${TARGET}" == "pgi" ]; then
-    #    module swap pgi pgi/10.5.0
-    #fi
     module load python
-    export LDFLAGS="-pgcpplibs"
+    if [ "$TARGET" == "pgi" ]; then
+        export CC=pgcc
+        export CXX=pgCC
+        export FC=pgf90
+        export LDFLAGS="-pgcpplibs"
+        WITHDART="--with-dataspaces=/global/homes/p/pnorbert/dataspaces/1.1.0/$TARGET"
+    elif [ "$TARGET" == "gnu" ]; then
+        export CC=gcc
+        export CXX=g++
+        export FC=gfortran
+        export LDFLAGS=""
+        WITHDART="--with-dataspaces=/global/homes/p/pnorbert/dataspaces/1.1.0/$TARGET"
+    elif [ "$TARGET" == "intel" ]; then
+        export CC=icc
+        export CXX=icpc
+        export FC=ifort
+        export LDFLAGS=""
+        WITHDART=""
+    else
+        echo "TARGET must be pgi or gnu or intel"
+        exit 1
+    fi
     export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK"
     export CFLAGS="-fPIC"
-    #./configure --prefix=/project/projectdirs/m499/adios \
-    ./configure --prefix=/global/homes/p/pnorbert/adios/1.3.1/hopper/$TARGET \
+    ./configure --prefix=/global/homes/p/pnorbert/adios/1.4.1/hopper/$TARGET \
         --enable-dependency-tracking \
         --with-mxml=$HOME/mxml/mxml.hopper \
         --with-lustre=/usr \
+        $WITHDART \
         --without-hdf5 --without-netcdf
 
 
