dataspaces/portals still using old library names

diff --git a/runconf b/runconf
--- a/runconf
+++ b/runconf
@@ -9,7 +9,13 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
     ########
     # Sith #
     ########
-    TARGET=pgi
+    source /etc/profile.d/modules.sh
+    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
+
+    if [ -z "$TARGET" ]; then
+        echo "Cannot determine Programming environment. Exit"
+        exit 1
+    fi
     echo "Configure on SITH for $TARGET env."
     source /etc/profile.d/modules.sh
     module unload hdf5
@@ -245,7 +251,7 @@ elif [ `hostname | cut -c 1-8` == "jaguarpf" ]; then
         module unload PrgEnv-pgi
         module unload PrgEnv-intel
         module unload PrgEnv-cray
-        module unload xt-papi
+        #module unload papi
         module load PrgEnv-$TARGET
         module swap xtpe-interlagos xtpe-istanbul
         #module load szip
@@ -255,6 +261,7 @@ elif [ `hostname | cut -c 1-8` == "jaguarpf" ]; then
         #export CC=mpicc
         #export FC=mpif90
         CFLAGS="-g -fPIC" ./configure --prefix=/ccs/proj/e2e/qliu/ADIOS/test.$TARGET \
+            --host=jaguar --host_alias=jaguar  \
             --enable-dependency-tracking \
             #--with-hdf5=/opt/cray/hdf5/1.8.7/pgi/109 \
             #--with-phdf5=/opt/cray/hdf5-parallel/1.8.7/pgi/109 \
@@ -289,19 +296,21 @@ elif [ `hostname | cut -c 1-8` == "jaguarpf" ]; then
         module unload PrgEnv-pgi
         module unload PrgEnv-intel
         module unload PrgEnv-cray
-        module unload xt-papi
+        #module unload papi
         #module unload xtpe-quadcore
         module load PrgEnv-$TARGET
+        module swap xtpe-interlagos xtpe-istanbul
+        module load dataspaces/1.0.0
         if [ "$TARGET" == "pgi" ]; then
-            module swap pgi pgi/11.8.0
+            #module swap pgi pgi/11.8.0
             # NSSI needs -pgcpplibs flag 
             export LDFLAGS="-pgcpplibs" 
-            WITHDART="--with-dataspaces=/ccs/proj/e2e/dataspaces/xk6/$TARGET"
+            #WITHDART="--with-dataspaces=/ccs/proj/e2e/dataspaces/xk6/$TARGET"
         elif [ "$TARGET" == "gnu" ]; then
             # NSSI needs libstdc++
             export EXTRA_LIBS="/opt/gcc/4.4.4/snos/lib64/libstdc++.a"
             module swap gcc gcc/4.4.4
-            WITHDART="--with-dataspacesss=/ccs/proj/e2e/dataspaces/xk6/$TARGET"
+            #WITHDART="--with-dataspacesss=/ccs/proj/e2e/dataspaces/xk6/$TARGET"
         else
             WITHDART=""
         fi
@@ -310,7 +319,7 @@ elif [ `hostname | cut -c 1-8` == "jaguarpf" ]; then
         #module load hdf5-parallel
         #module load netcdf-hdf5parallel
         module load szip
-        module load xt-papi
+        #module load papi
         module load mxml
         # use the two lines below for openmpi
         #export CC=mpicc
@@ -320,7 +329,10 @@ elif [ `hostname | cut -c 1-8` == "jaguarpf" ]; then
         #./configure --prefix=/ccs/proj/e2e/pnorbert/ADIOS/xt5.$TARGET \
         ./configure --prefix=/ccs/proj/fus022/norbert/RMP/adios.xt5.$TARGET \
         --enable-dependency-tracking \
-        $WITHDART \
+        --with-cray-pmi=/opt/cray/pmi/default \
+        --with-cray-ugni-incdir=/opt/cray/gni-headers/default/include \
+        --with-cray-ugni-libdir=/opt/cray/ugni/default/lib \
+        --with-dataspaces=$DATASPACES_DIR 
         #--with-netcdf=/opt/cray/netcdf/3.6.2/netcdf-${TARGET} \
         #--with-hdf5=/sw/xt5/hdf5/1.8.2/cnl2.1_gnu4.2.0 \
         #--with-nc4par=/opt/cray/netcdf-hdf5parallel/4.0.1.3/netcdf-hdf5parallel-$TARGET \
