Cosmetics for 1.3.1 release; chester build for XK6;

diff --git a/runconf b/runconf
--- a/runconf
+++ b/runconf
@@ -9,7 +9,8 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
     ########
     # Sith #
     ########
-    echo "Configure on SITH"
+    TARGET=pgi
+    echo "Configure on SITH for $TARGET env."
     source /etc/profile.d/modules.sh
     module unload hdf5
     module unload netcdf
@@ -18,9 +19,10 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
     module unload PE-intel
     module unload PE-pathscale
     module unload pgi gcc intel pathscale
-    TARGET=pgi
+    module unload python
     module load PE-$TARGET
     module load mxml
+    module load python
     # Use both seq hdf5 (for utils) and 
     #   parallel hdf5 (for PHDF5 method)
     module load hdf5/1.8.5
@@ -56,7 +58,7 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
         export CXX=icpc
         export FC=ifort
     else
-        echo "TARGET must be pgi or gnu"
+        echo "TARGET must be pgi or gnu or intel"
         exit 1
     fi
         
@@ -80,7 +82,8 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
 
 
 elif [ `hostname | cut -c 1-4` == "lens" ]; then
-    echo "Configure on LENS"
+    TARGET=pgi
+    echo "Configure on LENS for $TARGET env."
     source /etc/profile.d/modules.sh
     module unload hdf5
     module unload netcdf
@@ -88,7 +91,6 @@ elif [ `hostname | cut -c 1-4` == "lens" ]; then
     module unload PE-pgi
     module unload PE-pathscale
     module unload pgi
-    TARGET=pgi
     module load PE-$TARGET
     # Use both seq hdf5 (for utils) and 
     #   parallel hdf5 (for PHDF5 method)
@@ -127,7 +129,117 @@ elif [ `hostname | cut -c 1-4` == "lens" ]; then
         --without-datatap \
         --with-dmalloc=/ccs/proj/e2e/qliu/dmalloc.lens.$TARGET
 
-elif [ `hostname | cut -c 1-6` == "jaguar" -o `hostname | cut -c 1-7` == "chester" ]; then
+
+elif [ `hostname | cut -c 1-7` == "chester" ]; then
+
+      ###############
+      # Chester XK6 #
+      ###############
+      TARGET=pgi
+      echo "Configure on Chester (XK6) for $TARGET env."
+      export CC=cc
+      #export CFLAGS="-Wall -g" 
+      export FC=ftn
+      export CXX=CC
+      source /opt/modules/default/etc/modules.sh
+      module unload szip
+      module unload hdf5
+      module unload netcdf
+      module unload netcdf-hdf5parallel
+      module unload hdf5-parallel
+      module unload PrgEnv-gnu
+      module unload PrgEnv-pgi
+      module unload PrgEnv-intel
+      module unload PrgEnv-cray
+      module unload papi
+      module load PrgEnv-$TARGET
+      #module load szip
+      #module load xt-papi
+      module load mxml
+      # use the two lines below for openmpi
+      #export CC=mpicc
+      #export FC=mpif90
+      CFLAGS="-g -fPIC" ./configure --prefix=/ccs/proj/e2e/adios/xk6.$TARGET \
+          --enable-dependency-tracking 
+#            --without-portals \
+#            --with-lustre=/opt/xt-lustre-ss/2.2_1.6.5/usr \
+#            --with-dmalloc=/ccs/proj/e2e/qliu/dmalloc.$TARGET \
+#            --enable-research-transports \
+#            --with-netcdf=/opt/cray/netcdf/3.6.2/netcdf-${TARGET} \
+#            --with-nc4par=/opt/cray/netcdf-hdf5parallel/4.0.1.3/netcdf-hdf5parallel-$TARGET \
+#            --with-phdf5=/opt/cray/hdf5-parallel/1.8.4.1/hdf5-parallel-$TARGET \
+#            --with-hdf5=/sw/xt5/hdf5/1.8.2/cnl2.1_gnu7.2.3 \
+#            --with-hdf5=/sw/xt5/hdf5/1.8.2/cnl2.1_gnu4.2.0 \
+#            --with-mxml=/ccs/proj/e2e/pnorbert/mxml.xt5.$TARGET \
+            
+
+elif [ `hostname | cut -c 1-5` == "smoky" ]; then
+
+    #########
+    # Smoky #
+    #########
+    echo "Configure on SMOKY"
+    source /etc/profile.d/modules.sh
+    module unload hdf5
+    module unload netcdf
+    module unload PE-gnu
+    module unload PE-pgi
+    module unload PE-intel
+    module unload PE-pathscale
+    module unload pgi gcc intel pathscale
+    TARGET=pgi
+    module load PE-$TARGET
+    # Use both seq hdf5 (for utils) and 
+    #   parallel hdf5 (for PHDF5 method)
+    #module load hdf5/1.8.5
+    #SEQ_HDF5_DIR=$HDF5_DIR
+    #SEQ_HDF5_DIR=/sw/smoky/hdf5/1.8.5/centos5.5_pgi10.4
+    #SEQ_HDF5_CLIB=$HDF5_CLIB
+    #module unload hdf5/1.8.5
+    #module load hdf5/1.8.5_ompi1.4.2
+    #PAR_HDF5_DIR=$HDF5_DIR
+    #PAR_HDF5_DIR=/sw/smoky/hdf5/1.8.5/centos5.5_pgi10.4_ompi1.4.2
+    #PAR_HDF5_CLIB=$HDF5_CLIB
+    export MPICC=mpicc
+    export MPICXX=mpiCC
+    export MPIFC=mpif90
+    if [ "$TARGET" == "pgi" ]; then
+        export CC=pgcc
+        export CXX=pgCC
+        export FC=pgf90
+    elif [ "$TARGET" == "gnu" ]; then
+        export CC=gcc
+        export CXX=g++
+        export FC=gfortran
+    elif [ "$TARGET" == "intel" ]; then
+        export CC=icc
+        export CXX=icpc
+        export FC=ifort
+    else
+        echo "TARGET must be pgi or gnu"
+        exit 1
+    fi
+        
+    export CFLAGS="-g -fPIC" 
+    ./configure --prefix=/ccs/proj/e2e/pnorbert/ADIOS/smoky.$TARGET \
+        --enable-dependency-tracking \
+        --enable-research-transports  \
+        --with-mxml=/ccs/proj/e2e/pnorbert/mxml.smoky.$TARGET \
+        --without-hdf5 --without-phdf5 \
+        --without-netcdf --without-nc4par \
+        --with-lustre=/usr \
+        --without-datatap --without-infiniband \
+        #--with-phdf5=${PAR_HDF5_DIR} \
+        #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
+        #--with-hdf5=${SEQ_HDF5_DIR} \
+        #--with-hdf5-libs="${SEQ_HDF5_CLIB}" \
+        #--with-netcdf=${SEQ_NC_DIR} \
+        #--with-netcdf-libs="${SEQ_NC_CLIB}" \
+        #--with-nc4par=${PAR_NC_DIR} \
+        #--with-nc4par-libs="${PAR_NC_CLIB}" \
+
+
+elif [ `hostname | cut -c 1-6` == "jaguar" ]; then
 
     BUILD_STAGING=false
     if [ $BUILD_STAGING == "false" ]; then
@@ -135,7 +247,8 @@ elif [ `hostname | cut -c 1-6` == "jaguar" -o `hostname | cut -c 1-7` == "cheste
         ##########
         # Jaguar #
         ##########
-        echo "Configure on JAGUAR"
+        TARGET=pgi
+        echo "Configure on JAGUAR (XT5) for $TARGET env."
         export CC=cc
         #export CFLAGS="-Wall -g" 
         export FC=ftn
@@ -151,7 +264,6 @@ elif [ `hostname | cut -c 1-6` == "jaguar" -o `hostname | cut -c 1-7` == "cheste
         module unload PrgEnv-intel
         module unload PrgEnv-cray
         module unload xt-papi
-        TARGET=pgi
         module load PrgEnv-$TARGET
         #module load szip
         #module load xt-papi
@@ -178,7 +290,8 @@ elif [ `hostname | cut -c 1-6` == "jaguar" -o `hostname | cut -c 1-7` == "cheste
         ##########
         # Jaguar #
         ##########
-        echo "Configure on JAGUAR including staging methods"
+        TARGET=pgi
+        echo "Configure on JAGUAR including staging methods for $TARGET env."
         export CC=cc
         export FC=ftn
         export CXX=CC
@@ -194,7 +307,6 @@ elif [ `hostname | cut -c 1-6` == "jaguar" -o `hostname | cut -c 1-7` == "cheste
         module unload PrgEnv-cray
         module unload xt-papi
         #module unload xtpe-quadcore
-        TARGET=pgi
         module load PrgEnv-$TARGET
         if [ "$TARGET" == "pgi" ]; then
             module swap pgi pgi/10.4.0
@@ -237,6 +349,7 @@ elif [ `hostname | cut -c 1-6` == "jaguar" -o `hostname | cut -c 1-7` == "cheste
     
     fi
     
+
 elif [ `hostname | cut -c 1-4` == "euge" ]; then
     ###################
     # Eugene BlueGene #
@@ -265,31 +378,13 @@ elif [ `hostname | cut -c 1-4` == "euge" ]; then
             --with-hdf5-libs="$HDF5_CLIB" \
             --without-phdf5
 
-
-elif [ `hostname | cut -c 1-4` == "lens" ]; then
-
-    ########
-    # Lens #
-    ########
-    echo "Configure on LENS"
-    export CC=mpicc
-    export CXX=mpiCC
-    source /etc/profile.d/modules.sh
-    module load hdf5
-    #module load netcdf
-    CFLAGS="-fPIC" ./configure --prefix=/ccs/proj/e2e/pnorbert/adios/lens \
-        --enable-dependency-tracking \
-        --with-mxml=/ccs/proj/e2e/pnorbert/mxml \
-        --without-netcdf
-        #--with-hdf5=/sw/analysis-x64/hdf5/1.6.7/sl5.0_pgi7.1.5_ompi1.2.6 \
-        #--with-netcdf=/sw/analysis-x64/netcdf/3.6.2/sl5.0_pgi7.1.5
-    
     
 elif [ `hostname | cut -c 1-4` == "nid0" ]; then
     ############
     # Franklin #
     ############
-    echo "Configure on FRANKLIN"
+    TARGET=pgi
+    echo "Configure on FRANKLIN for $TARGET env."
     export CC=cc
     export CXX=CC
     export FC=ftn
@@ -301,7 +396,6 @@ elif [ `hostname | cut -c 1-4` == "nid0" ]; then
     module unload PrgEnv-pgi
     module unload PrgEnv-pathscale
     module unload PrgEnv-cray
-    TARGET=pgi
     module load PrgEnv-$TARGET
     #if [ "${TARGET}" == "pgi" ]; then
     #    module swap pgi pgi/10.5.0
@@ -319,6 +413,7 @@ elif [ `hostname | cut -c 1-4` == "nid0" ]; then
         --with-nc4par=/opt/cray/netcdf-hdf5parallel/4.1.1.0/netcdf-hdf5parallel-${TARGET} \
         --with-dart=/global/homes/p/pnorbert/dart.0628.pgi
     
+
 elif [ `hostname | cut -c 1-4` == "dyn9" -o `hostname | cut -c 1-3` == "pnb" ]; then
 
     #######
@@ -339,6 +434,7 @@ elif [ `hostname | cut -c 1-4` == "dyn9" -o `hostname | cut -c 1-3` == "pnb" ]; 
         --with-phdf5=/opt/hdf5 \
         --with-hdf5=/opt/hdf5.seq
 
+
 elif [ `hostname | cut -c 1-7` == "ubuntu" ]; then
 
     #########################
@@ -353,6 +449,7 @@ elif [ `hostname | cut -c 1-7` == "ubuntu" ]; then
         #--with-phdf5=/usr/local \
         #--with-netcdf=/usr 
 
+
 elif [ `hostname | cut -c 1-6` == "tomato" ]; then
 
     #########################
@@ -366,6 +463,7 @@ elif [ `hostname | cut -c 1-6` == "tomato" ]; then
         --with-phdf5=/home/thkorde/local \
         --with-hdf5=/home/thkorde/local \
         --with-netcdf=/home/thkorde/local
+
 
 elif [ `hostname | cut -c 1-4` == "qliu" ]; then
 
@@ -382,31 +480,11 @@ elif [ `hostname | cut -c 1-4` == "qliu" ]; then
         #--with-hdf5=/home/thkorde/local \
         #--with-netcdf=/home/thkorde/local
 
-elif [ `hostname | cut -c 1-5` == "smoky" ]; then
-
-    #########
-    # Smoky #
-    #########
-    echo "Configure on SMOKY"
-export CC=mpicc
-export FC=mpif90
-# use the two lines below for openmpi
-#export CC=mpicc
-#export FC=mpif90
-# use for both MPI implementations
-./configure --prefix=/ccs/home/ge1/work/smoky \
-            --enable-dependency-tracking \
-            --with-mxml=/ccs/home/ge1/work/smoky \
-            --with-hdf5=/sw/xt5/hdf5/1.6.7/cnl2.1_gnu4.2.4 \
-            --with-hdf5-libdir="/sw/xt5/hdf5/1.6.7/cnl2.1_gnu4.2.4/lib -L/sw/xt5/szip/2.1/sles10.1_gnu4.2.4/lib -lsz -lz" \
-            --with-phdf5=/sw/xt5/hdf5/1.6.7/cnl2.1_gnu4.2.4_par \
-            --with-phdf5-libdir="/sw/xt5/hdf5/1.6.7/cnl2.1_gnu4.2.4_par/lib -L/sw/xt5/szip/2.1/sles10.1_gnu4.2.4/lib -lsz -lz" \
-            --with-netcdf=/sw/xt5/netcdf/3.6.2/sles10.1_gnu4.2.0
 
 else
-    echo "Could not determine what machine is this"
-    echo "This script is for configuring adios on the authors' machines"
-    echo "You can study it to figure out how to configure adios on your system"
+    echo "Could not determine what machine is this."
+    echo "This script is for configuring adios on the authors' machines."
+    echo "You can study it to figure out how to configure adios on your system."
 fi
     
     
