added Rhea to runconf

diff --git a/runconf b/runconf
--- a/runconf
+++ b/runconf
@@ -111,6 +111,105 @@ if [ `hostname | cut -c 1-4` == "sith" ]; then
         #--with-datatap=/ccs/home/habbasi/work/ewok/
         #--enable-datatap=ib
 
+elif [ `hostname | cut -c 1-4` == "rhea" ]; then
+
+    ########
+    # Rhea #
+    ########
+    source /etc/profile.d/modules.sh
+    TARGET=`module list 2>&1 | grep "PE"- | sed "s/^.*PE-\([a-z]*\).*/\1/"`
+
+    if [ -z "$TARGET" ]; then
+        echo "Cannot determine Programming environment. Exit"
+        exit 1
+    fi
+    echo "Configure on Rhea for $TARGET env. for user $USER"
+    source /etc/profile.d/modules.sh
+    module unload mxml
+    module unload hdf5
+    module unload netcdf
+    module unload PE-gnu
+    module unload PE-pgi
+    module unload PE-intel
+    module unload PE-pathscale
+    module unload pgi gcc intel pathscale
+    module unload python
+    module load PE-$TARGET
+    module load mxml
+    MXMLDIR=$MXML_DIR
+    module unload mxml
+    module load python
+    # Use both seq hdf5 (for utils) and 
+    #   parallel hdf5 (for PHDF5 method)
+    module load hdf5/1.8.11
+    SEQ_HDF5_DIR=$HDF5_DIR
+    SEQ_HDF5_CLIB=$HDF5_CLIB
+    module unload hdf5
+    module load hdf5-parallel/1.8.11
+    PAR_HDF5_DIR=$HDF5_DIR
+    PAR_HDF5_CLIB=$HDF5_CLIB
+    module unload hdf5
+    # Seq. and Parallel NetCDF 4 
+    module load netcdf/4.1.3
+    SEQ_NC_DIR=$NETCDF_DIR
+    SEQ_NC_CLIB=$NETCDF_CLIB
+    module unload netcdf
+    #module load netcdf/4.1.3_par
+    #PAR_NC_DIR=$NETCDF_DIR
+    #PAR_NC_CLIB=$NETCDF_CLIB
+    #module unload netcdf
+    #module load szip
+    #module load bzip2
+    #module load dataspaces/1.4.0
+    export MPICC=mpicc
+    export MPICXX=mpiCC
+    export MPIFC=mpif90
+    if [ "$TARGET" == "pgi" ]; then
+        export CC=pgcc
+        export CXX=pgCC
+        export FC=pgf90
+        WITHFLEX="--with-flexpath=/ccs/proj/e2e/chaos/sith/$TARGET"
+    elif [ "$TARGET" == "gnu" ]; then
+        export CC=gcc
+        export CXX=g++
+        export FC=gfortran
+        WITHFLEX="--with-flexpath=/ccs/proj/e2e/chaos/sith/$TARGET"
+    elif [ "$TARGET" == "intel" ]; then
+        export CC=icc
+        export CXX=icpc
+        export FC=ifort
+        WITHFLEX=""
+    else
+        echo "TARGET must be pgi or gnu or intel"
+        exit 1
+    fi
+        
+    export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK" 
+    export CFLAGS="-g -fPIC" 
+    $SRCDIR/configure --prefix=/ccs/proj/e2e/$USER/ADIOS/rhea.$TARGET \
+        --config-cache \
+        --enable-dependency-tracking \
+        --enable-research-transports \
+        --with-lustre \
+        --with-mxml=$MXMLDIR 
+        #--with-hdf5=${SEQ_HDF5_DIR} \
+        #--with-hdf5-libs="${SEQ_HDF5_CLIB}" \
+        #--with-phdf5=${PAR_HDF5_DIR} \
+        #--with-phdf5-libs="${PAR_HDF5_CLIB}" \
+        #--with-netcdf=${SEQ_NC_DIR} \
+        #--with-netcdf-libs="${SEQ_NC_CLIB}" \
+        #--with-nc4par=${PAR_NC_DIR} \
+        #--with-nc4par-libs="${PAR_NC_CLIB}" \
+        #--with-zlib \
+        #--with-bzip2=$BZIP2_DIR \
+        #--with-dataspaces=$DATASPACES_DIR \
+        #$WITHFLEX \
+        #--with-aplod=/ccs/proj/e2e/ncsu/sith.gnu \
+        #--with-isobar=/ccs/proj/e2e/ncsu/sith.gnu \
+        #--with-fgr=/ccs/proj/e2e/qliu/tap \
+        #--with-glib=/ccs/proj/e2e/qliu/glib
+        #--with-szip=$SZIP_DIR \
+
 elif [ `hostname | cut -c 1-4` == "yona" ]; then
 
     ########
