added Kraken

diff --git a/runconf b/runconf
--- a/runconf
+++ b/runconf
@@ -673,6 +673,55 @@ elif [ `hostname | cut -c 1-6` == "hopper" ]; then
         --without-hdf5 --without-netcdf
 
 
+
+elif [ `hostname | cut -c 1-6` == "kraken" ]; then
+    ##########
+    # Kraken #
+    ##########
+    source /opt/modules/default/etc/modules.sh
+    TARGET=`module list 2>&1 | grep PrgEnv | sed "s/^.*Env-\([a-z]*\).*/\1/"`
+
+    if [ -z "$TARGET" ]; then
+        echo "Cannot determine Programming environment. Exit"
+        exit 1
+    fi
+    echo ""
+    echo "Configure for the $TARGET compiler"
+    echo ""
+    export CC=cc
+    export FC=ftn
+    export CXX=CC
+    module unload szip
+    module unload hdf5
+    module unload netcdf
+    module unload hdf5-parallel
+    module unload netcdf-hdf5parallel
+    module unload xt-papi
+    module unload papi
+    if [ "$TARGET" == "pgi" ]; then
+        #module swap pgi pgi/10.4.0
+        # NSSI needs -pgcpplibs flag 
+        export EXTRA_LIBS=""
+        export LDFLAGS="-pgcpplibs" 
+    elif [ "$TARGET" == "gnu" ]; then
+        # NSSI needs libstdc++
+        export EXTRA_LIBS="/opt/gcc/4.4.4/snos/lib64/libstdc++.a"
+        export LDFLAGS="" 
+        #module swap gcc gcc/4.4.4
+    fi
+
+    module load szip
+    module load mxml
+    module load subversion
+    export CPPFLAGS="-DMPICH_IGNORE_CXX_SEEK" 
+    export CFLAGS="-fPIC -g -O0" 
+    ./configure --prefix=/nics/d/home/norbert/adios/$TARGET \
+        --enable-dependency-tracking \
+        --with-portals=yes \
+        --without-netcdf --without-nc4par --without-hdf5 --without-phdf5 \
+        --with-dataspaces=/nics/d/home/norbert/dart0628/$TARGET
+
+
 elif [ `hostname | cut -c 1-4` == "dyn9" -o `hostname | cut -c 1-3` == "pnb" ]; then
 
     #######
